title = "config"

[Connection]
token = "token"

[Ranks]
1 = "940705698537406484"
2 = "940705742690873387"

[Other]
status = "aksdmaksmdk"
statussuffix = 2 # 0 - playing, 1 - Listening, 2 - Competing, 3 - streaming, 4 - Watching
