title = "config"

[Connection]
token = "ODM4NDE0ODMzNzkwNDg0NTUx.YI6wqQ.m7HEXqQEA0D3mmtWvlmrzHu6NPk"

[Ranks]
1 = "1111"
2 = "2222"

[Other]
status = "aksdmaksmdk"
statussuffix = 2 # 0 - playing, 1 - Listening, 2 - Competing, 3 - streaming, 4 - Watching
